### ISSUE TITLE
Trun for help what kinds of zhe txt file can be input

### ISSUE THREAD

**Issue by xiaosongshine** [jphdotam/BARD-labeller#1]
Thinks for your BARD-labeller
I want to use it to label ECG.
But I don’t know what kinds of zhe txt file can be input
I try some kinds of ,but it can not  work.
Could you please sent some data to test,Best think
my email: xiaosongmiss@hotmail.com

**Comment by jphdotam** [comment]
Hi there,

The format for the BARD text file is as follows. There is a header section describing each channel, then a data section with a comma-separate column for each channel, with a row per sample.

```
[Header]
File Type: 1
Version: 2
Channels exported: 12
Samples per channel: 4834
Start time: 13:56:08
End time: 13:56:13
Ch. Info. Pointer: 320
Stamp Data: C
Mux format: 0
Mux Block Size: 
Data Format 1
Sample Rate: 1000Hz
Channel #:   1
Label: I
Range: 5mv 
Low: .05Hz
High: 100Hz
Sample rate: 1000Hz
Color: 00FF00
Scale: -7
Channel #:   2
Label: II
Range: 5mv 
Low: .05Hz
High: 100Hz
Sample rate: 1000Hz
Color: 00FF00
Scale: -7
Channel #:   3
Label: III
Range: 5mv 
Low: .05Hz
High: 100Hz
Sample rate: 1000Hz
Color: 00FF00
Scale: -7
Channel #:   4
Label: aVR
Range: 5mv 
Low: .05Hz
High: 100Hz
Sample rate: 1000Hz
Color: 00FF00
Scale: -7
Channel #:   5
Label: aVL
Range: 5mv 
Low: .05Hz
High: 100Hz
Sample rate: 1000Hz
Color: 00FF00
Scale: -7
Channel #:   6
Label: aVF
Range: 5mv 
Low: .05Hz
High: 100Hz
Sample rate: 1000Hz
Color: 00FF00
Scale: -7
Channel #:   7
Label: V1
Range: 5mv 
Low: .05Hz
High: 100Hz
Sample rate: 1000Hz
Color: 00FF00
Scale: -7
Channel #:   8
Label: V2
Range: 5mv 
Low: .05Hz
High: 100Hz
Sample rate: 1000Hz
Color: 00FF00
Scale: -7
Channel #:   9
Label: V3
Range: 5mv 
Low: .05Hz
High: 100Hz
Sample rate: 1000Hz
Color: 00FF00
Scale: -7
Channel #:  10
Label: V4
Range: 5mv 
Low: .05Hz
High: 100Hz
Sample rate: 1000Hz
Color: 00FF00
Scale: -7
Channel #:  11
Label: V5
Range: 5mv 
Low: .05Hz
High: 100Hz
Sample rate: 1000Hz
Color: 00FF00
Scale: -7
Channel #:  12
Label: V6
Range: 5mv 
Low: .05Hz
High: 100Hz
Sample rate: 1000Hz
Color: 00FF00
Scale: -7

[Data]
2592,656,-1936,-1648,2256,-640,-560,-992,-2848,848,1248,224
2592,688,-1920,-1664,2256,-608,-544,-976,-2832,880,1280,224
2624,720,-1920,-1696,2272,-592,-544,-944,-2800,896,1296,224
2672,768,-1920,-1744,2288,-576,-512,-912,-2768,912,1312,224
2688,768,-1920,-1744,2304,-592,-496,-880,-2736,944,1344,240
2688,752,-1936,-1744,2304,-592,-464,-848,-2704,976,1360,256
2656,704,-1952,-1712,2304,-624,-432,-800,-2672,1008,1392,256

```

**Comment by xiaosongshine** [comment]
Thank you very much
Thanks for you work
I tested yuor data is ok
I will adapt my data into this format
this is my blog:https://blog.csdn.net/xiaosongshine
Nice to meet you

**Comment by xiaosongshine** [comment]
Dear Dr. James Howard,
 
Thanks for your sample text file. I am wondering if you could provide us a sample text file with full data in it please.
 
Also please help us to interpret some key channel parameters such as Range: 5mv, Color: 00FF00 and Scale: -7.
 
As you have shown that the data section as below:
[Data]
2592,656,-1936,-1648,2256,-640,-560,-992,-2848,848,1248,224
…
Are these integers of signed 16 bit? What are the true values of the first row of signed integer, 2592, 656, -1936 etc.? 


More questions regarding to the header:

Ch. Info. Pointer: 320
Stamp Data: C
Mux format: 0
Mux Block Size: 
Data Format 1

 
Many Thanks.
